In [1]:
import numpy as np

In [2]:
li = np.array([[1, 2, 3], [7, 3, 6]])

In [3]:
li

array([[1, 2, 3],
       [7, 3, 6]])

In [4]:
li[0]

array([1, 2, 3])

In [5]:
li[1]

array([7, 3, 6])

In [6]:
li[0][0]

1

In [10]:
li[0][1]

2

In [11]:
li.shape

(2, 3)

In [12]:
np.__version__

'1.21.5'

In [16]:
li[0][1] = 10

In [17]:
li

array([[ 1, 10,  3],
       [ 7,  3,  6]])

In [18]:
li[0] = 1

In [19]:
li

array([[1, 1, 1],
       [7, 3, 6]])

In [20]:
li[][1] = 2

SyntaxError: invalid syntax (3197704390.py, line 1)

In [21]:
li[:][1] = 2

In [22]:
li

array([[1, 1, 1],
       [2, 2, 2]])

In [23]:
li[1, 0] = 5

In [24]:
li

array([[1, 1, 1],
       [5, 2, 2]])

In [25]:
li[1, 0][1] = 6

TypeError: 'numpy.int32' object does not support item assignment

In [1]:
import numpy as np

In [3]:
li = np.array([[2.4,5,7], [6, 6, 3]])

In [4]:
li

array([[2.4, 5. , 7. ],
       [6. , 6. , 3. ]])

In [5]:
li.type

AttributeError: 'numpy.ndarray' object has no attribute 'type'

In [6]:
li.dype

AttributeError: 'numpy.ndarray' object has no attribute 'dype'

In [7]:
li.dtype

dtype('float64')

In [8]:
li.shape

(2, 3)

In [9]:
li[0]

array([2.4, 5. , 7. ])

In [10]:
li[1]

array([6., 6., 3.])

In [11]:
li

array([[2.4, 5. , 7. ],
       [6. , 6. , 3. ]])

In [12]:
li[:,0] = 10

In [13]:
li

array([[10.,  5.,  7.],
       [10.,  6.,  3.]])

In [14]:
type(li)

numpy.ndarray

In [15]:
l = [20, 10, 33]

In [16]:
li[0] = l

In [17]:
li

array([[20., 10., 33.],
       [10.,  6.,  3.]])

In [18]:
type(li[0])

numpy.ndarray