In [1]:
import numpy as np

In [3]:
array_a = np.array([1,3,5])
array_a

array([1, 3, 5])

In [4]:
array_b = np.array([[2], [5]])
array_b

array([[2],
       [5]])

In [5]:
array_a + array_b

array([[ 3,  5,  7],
       [ 6,  8, 10]])

In [6]:
np.add(array_a, array_b)

array([[ 3,  5,  7],
       [ 6,  8, 10]])

In [7]:
matrix_c = np.array([[1, 4, 7], [7, 5, 9]])
matrix_c

array([[1, 4, 7],
       [7, 5, 9]])

In [8]:
np.add(array_a, matrix_c)

array([[ 2,  7, 12],
       [ 8,  8, 14]])

In [9]:
array_a + matrix_c

array([[ 2,  7, 12],
       [ 8,  8, 14]])

In [10]:
np.add(array_b, matrix_c)

array([[ 3,  6,  9],
       [12, 10, 14]])

In [11]:
array_b+matrix_c

array([[ 3,  6,  9],
       [12, 10, 14]])