In [1]:
import numpy as np

In [6]:
array_a = np.array([[1,3,5], [2, 5, 1]], np.float32)

In [7]:
array_a

array([[1., 3., 5.],
       [2., 5., 1.]], dtype=float32)

In [4]:
array_a.dtype

dtype('int32')

In [8]:
array_b = np.array([[1,3,5], [2, 5, 1]], np.complex64)

In [9]:
array_b

array([[1.+0.j, 3.+0.j, 5.+0.j],
       [2.+0.j, 5.+0.j, 1.+0.j]], dtype=complex64)

In [11]:
array_c = np.array([[1,3,5], [2, 5, 1]], np.bool_)
array_c

array([[ True,  True,  True],
       [ True,  True,  True]])