In [1]:
import numpy as np

In [2]:
np.__version__

'1.23.5'

In [2]:
li = [1, 3, 4]

In [4]:
li2 = [[4, 6, 2], [2, 7, 4]]

In [5]:
li

[1, 3, 4]

In [6]:
li2

[[4, 6, 2], [2, 7, 4]]

In [13]:
li3 = li + li2

In [14]:
li3

[1, 3, 4, [4, 6, 2], [2, 7, 4]]

In [12]:
li3[3]

[4, 6, 2]

In [15]:
li

[1, 3, 4]

In [16]:
li2

[[4, 6, 2], [2, 7, 4]]

In [17]:
li4 = li * li2

TypeError: can't multiply sequence by non-int of type 'list'

In [18]:
type(li)

list

In [19]:
li.dtype

AttributeError: 'list' object has no attribute 'dtype'

In [20]:
li.type


AttributeError: 'list' object has no attribute 'type'

In [21]:
li5 = li * li3[3]

TypeError: can't multiply sequence by non-int of type 'list'

In [22]:
ali = np.array(li)

In [23]:
ali

array([1, 3, 4])

In [24]:
type(ali)

numpy.ndarray

In [25]:
ali2 = np.array(li2)

In [26]:
ali2

array([[4, 6, 2],
       [2, 7, 4]])

In [27]:
ali3 = ali + ali2

In [28]:
ali3

array([[ 5,  9,  6],
       [ 3, 10,  8]])

In [29]:
ali4 = ali * ali2

In [30]:
ali4

array([[ 4, 18,  8],
       [ 2, 21, 16]])

In [31]:
ali6 = ali + ali4[0]

In [32]:
ali6

array([ 5, 21, 12])

In [33]:
ali7 = ali + ali6[:,0]

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [34]:
ali7 = ali[0] + ali6[:, 0]

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [35]:
ali3

array([[ 5,  9,  6],
       [ 3, 10,  8]])

In [36]:
ali4

array([[ 4, 18,  8],
       [ 2, 21, 16]])

In [37]:
ali3[:,0] 

array([5, 3])

In [38]:
ali4[:,0]

array([4, 2])

In [39]:
ali8 = ali3[:,0] + ali4[:,0]

In [40]:
ali8

array([9, 5])

In [41]:
ali4[-1]

array([ 2, 21, 16])

In [47]:
ali4[:,-2]

array([18, 21])