In [1]:
# Topics
'''
1. Indexing and slicing.
2. Iterating through arrays
3. Stacking together two arrays
4. Indexing with boolean arrays

'''

'\n1. Indexing and slicing.\n2. Iterating through arrays\n3. Stacking together two arrays\n4. Indexing with boolean arrays\n\n'

In [2]:
# Indexing and slicing
import numpy as np

li1 = np.array([1,2,3,4])


In [3]:
li1[1:3]

array([2, 3])

In [4]:
li1[-1]

4

In [5]:
li = np.array([[1,2], [3,4], [5,6]])

In [6]:
li

array([[1, 2],
       [3, 4],
       [5, 6]])

In [7]:
li[1:2, 1]

array([4])

In [8]:
li[-1, 1]

6

In [11]:
li.ravel()

array([1, 2, 3, 4, 5, 6])

In [12]:
for cell in li.flat:
    print(cell)

1
2
3
4
5
6


In [17]:
# Stacking two item together
l1 = np.arange(6).reshape(3, 2)

In [18]:
l1

array([[0, 1],
       [2, 3],
       [4, 5]])

In [19]:
l2 = np.arange(6, 12).reshape(3, 2)

In [20]:
l2

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [21]:
np.vstack((l1,l2))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [22]:
np.hstack((l1,l2))

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

In [23]:
li = np.arange(30).reshape(3,10)

In [24]:
li

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [26]:
# Spliting matrix at even parts
np.hsplit(li,2)

[array([[ 0,  1,  2,  3,  4],
        [10, 11, 12, 13, 14],
        [20, 21, 22, 23, 24]]),
 array([[ 5,  6,  7,  8,  9],
        [15, 16, 17, 18, 19],
        [25, 26, 27, 28, 29]])]

In [30]:
#  Creating an into bool value from int matrix

li = np.arange(20).reshape(4,5)

In [31]:
li

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [32]:
li2 = li > 10

In [33]:
li2

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [34]:
# Indexing array via a bool array
li[li2]

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [35]:
# Assigning value using array itself index
li[li2] = -1

In [36]:
li

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1]])