In [1]:
# Creating Num Array
import numpy as np

li = np.array([10, 30, 5])

In [2]:
li[0]
li[1]

30

In [3]:
li[1] = 50
li[1]

50

In [6]:
li2 = np.array([[1,2], [4,5], [7,8]])
li2

array([[1, 2],
       [4, 5],
       [7, 8]])

In [7]:
# How many dimantion this array has
li2.ndim

2

In [10]:
li2.itemsize
li2.dtype

dtype('int32')

In [11]:
#Changing Types
li3 = np.array([[1,2], [3,5]], dtype = np.float64)

In [12]:
li3


array([[1., 2.],
       [3., 5.]])

In [13]:
li3.itemsize


8

In [14]:
# Total Number of Elements
li3.size

4

In [16]:
# Shape of the array return the row x column
li3.shape
li2.shape

(3, 2)

In [17]:
# Complex Number creation of an matrix
li4 = np.array([[1,2], [3,5]], dtype = complex)

In [18]:
li4

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 5.+0.j]])

In [19]:
# Initialing with placeholder via shape
li5 = np.zeros((3,2))

In [20]:
li5

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [21]:
li5 = np.ones((2,3))

In [22]:
li5


array([[1., 1., 1.],
       [1., 1., 1.]])

In [23]:
# Create an array using range func
li6 = np.arange(3, 10)

In [24]:
li6

array([3, 4, 5, 6, 7, 8, 9])

In [25]:
li7 = np.arange(1,10,3)

In [26]:
li7

array([1, 4, 7])

In [28]:
# The uses of Linspace
li8 = np.linspace(1, 5, 8)
li8

array([1.        , 1.57142857, 2.14285714, 2.71428571, 3.28571429,
       3.85714286, 4.42857143, 5.        ])

In [3]:
import numpy as np
li10 = np.array([[1,2,3], [3,4,5]])

In [5]:
li10.shape


(2, 3)

In [6]:
# Reshape an array
li10.reshape((3,2))

array([[1, 2],
       [3, 3],
       [4, 5]])

In [7]:
# Flatant our array means trun into one dimention using ravel function
li10.ravel()

array([1, 2, 3, 3, 4, 5])

In [8]:
li10


array([[1, 2, 3],
       [3, 4, 5]])

In [9]:
# maximum & minimum of an matrix
li10.max()

5

In [10]:
li10.min()

1

In [11]:
# Sum all element of an matrix
li10.sum()

18

In [14]:
li10

array([[1, 2, 3],
       [3, 4, 5]])

In [12]:
# Sum column or rows
li10.sum(axis=0)

array([4, 6, 8])

In [13]:
li10.sum(axis=1)

array([ 6, 12])

In [15]:
#sqrt function on matrix
np.sqrt(li10)

array([[1.        , 1.41421356, 1.73205081],
       [1.73205081, 2.        , 2.23606798]])

In [16]:
# Standered deviation of an matrix
np.std(li10)

1.2909944487358056

In [17]:
# Matrix multiplication and add, subtraction etc.
li11 = np.array([[1,2],[3,4]])
li12 = np.array([[5,6], [7,8]])

In [18]:
li11+li12

array([[ 6,  8],
       [10, 12]])

In [19]:
li11*li12

array([[ 5, 12],
       [21, 32]])

In [20]:
li11/li12

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [21]:
li11-li12

array([[-4, -4],
       [-4, -4]])