In [1]:
# Itarating through Matrix
import numpy as np

li = np.arange(40).reshape(4,10)

In [2]:
li

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [3]:
for i in li:
    print(i)

[0 1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18 19]
[20 21 22 23 24 25 26 27 28 29]
[30 31 32 33 34 35 36 37 38 39]


In [5]:
for i in li.flatten():
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39


In [7]:
# nditer
for i in np.nditer(li, order='F'):
    print(i)

0
10
20
30
1
11
21
31
2
12
22
32
3
13
23
33
4
14
24
34
5
15
25
35
6
16
26
36
7
17
27
37
8
18
28
38
9
19
29
39


In [8]:
# nditer
for i in np.nditer(li, order='F', flags=['external_loop']):
    print(i)

[ 0 10 20 30]
[ 1 11 21 31]
[ 2 12 22 32]
[ 3 13 23 33]
[ 4 14 24 34]
[ 5 15 25 35]
[ 6 16 26 36]
[ 7 17 27 37]
[ 8 18 28 38]
[ 9 19 29 39]


In [10]:
# Squre of each element of my orginal matrix
for i in np.nditer(li, op_flags=['readwrite']):
    i[...] = i*i

In [11]:
li

array([[   0,    1,    4,    9,   16,   25,   36,   49,   64,   81],
       [ 100,  121,  144,  169,  196,  225,  256,  289,  324,  361],
       [ 400,  441,  484,  529,  576,  625,  676,  729,  784,  841],
       [ 900,  961, 1024, 1089, 1156, 1225, 1296, 1369, 1444, 1521]])

In [ ]:
# Iterating two array simultaniously
 for x,y in np.nditer([li, li])