In [1]:
import numpy as np

In [18]:
matrix_a = np.array([[1, 2, 3, 4, 7], [5, 6, 3, 8, 9], [7, 10, 0, -1, 8]])

In [19]:
matrix_a

array([[ 1,  2,  3,  4,  7],
       [ 5,  6,  3,  8,  9],
       [ 7, 10,  0, -1,  8]])

In [21]:
matrix_a.shape

(3, 5)

In [22]:
matrix_a[0].dtype

dtype('int32')

In [23]:
matrix_a[0]

array([1, 2, 3, 4, 7])

In [24]:
matrix_a[:]

array([[ 1,  2,  3,  4,  7],
       [ 5,  6,  3,  8,  9],
       [ 7, 10,  0, -1,  8]])

In [25]:
matrix_a[:,:]

array([[ 1,  2,  3,  4,  7],
       [ 5,  6,  3,  8,  9],
       [ 7, 10,  0, -1,  8]])

In [27]:
matrix_a[0:2,0:3]

array([[1, 2, 3],
       [5, 6, 3]])

In [28]:
matrix_a[0: :2, 1: :2] #stage slicing.

array([[ 2,  4],
       [10, -1]])