In [1]:
import numpy as np

### Type Casting

In [3]:
array_a = np.array([[1, 2, 3]], dtype=np.int64)
array_a

array([[1, 2, 3]], dtype=int64)

In [7]:
array_b = np.array([[1, 2, 3]], dtype=np.int64)
array_b

array([[1, 2, 3]], dtype=int64)

In [8]:
array_a + array_b

array([[2, 4, 6]], dtype=int64)

In [12]:
np.add(array_a, array_b, dtype=np.str_)

UFuncTypeError: ufunc 'add' did not contain a loop with signature matching types (<class 'numpy.dtype[int64]'>, <class 'numpy.dtype[int64]'>) -> <class 'numpy.dtype[str_]'>

### Running over an Axis

In [13]:
array_c = np.array([[1, 3, 6], [7, 9, 5]])
array_c

array([[1, 3, 6],
       [7, 9, 5]])

In [14]:
array_c + array_a

array([[ 2,  5,  9],
       [ 8, 11,  8]], dtype=int64)

In [15]:
np.add(array_a, array_c, axis=0)

TypeError: add() got an unexpected keyword argument 'axis'

In [17]:
np.sum(array_c[0])

10

In [20]:
np.mean(array_c, axis=1)

array([3.33333333, 7.        ])